services:

  mysql:
    image: mysql:latest
    container_name: GraphQL-demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: GraphQL-demo
      MYSQL_DATABASE: GraphQL-demo
      MYSQL_USER: GraphQL-demo
      MYSQL_PASSWORD: GraphQL-demo
    ports:
      - "3306:3306"
    networks:
      - GraphQL-demo
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      
networks:
    GraphQL-demo:
        driver: bridge